### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ScriptInfra** [AaronPLopez/SystemLogParser#5]
Hello! I would like to inquire if there are any future plans to support the System Log Parser installation on Linux? Thank you!

**Comment by AaronPLopez** [comment]
Hello,
Thank you for your interest in System Log Parser.
This is something that has been looked into and would most likely involve a
port to .NET 8 in order to get the runtime for Linux and Mac. Of course,
this port would only support slp.exe (the command-line version of System
Log Parser).
However, there is no timeline yet for this effort.


Aaron

**Comment by ScriptInfra** [comment]
Hello Aaron, thank you very much for this information and your expedient response!
